### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by AstraLuma** [dbaumgarten/yodk#83] opened 2021-08-15 06:13 UTC
(with no `~/go`)

```
🐚 go get -v github.com/dbaumgarten/yodk
github.com/dbaumgarten/yodk (download)
created GOPATH=/home/astraluma/go; see 'go help gopath'
github.com/abiosoft/ishell (download)
github.com/abiosoft/readline (download)
github.com/fatih/color (download)
github.com/mattn/go-colorable (download)
github.com/mattn/go-isatty (download)
get "golang.org/x/sys/unix": found meta tag get.metaImport{Prefix:"golang.org/x/sys", VCS:"git", RepoRoot:"https://go.googlesource.com/sys"} at //golang.org/x/sys/unix?go-get=1
get "golang.org/x/sys/unix": verifying non-authoritative meta tag
golang.org/x/sys (download)
github.com/flynn-archive/go-shlex (download)
github.com/jinzhu/copier (download)
github.com/elazarl/go-bindata-assetfs (download)
get "gopkg.in/yaml.v2": found meta tag get.metaImport{Prefix:"gopkg.in/yaml.v2", VCS:"git", RepoRoot:"https://gopkg.in/yaml.v2"} at //gopkg.in/yaml.v2?go-get=1
gopkg.in/yaml.v2 (download)
github.com/google/go-dap (download)
github.com/pmezard/go-difflib (download)
github.com/mitchellh/go-homedir (download)
github.com/spf13/cobra (download)
github.com/spf13/pflag (download)
github.com/spf13/viper (download)
github.com/fsnotify/fsnotify (download)
github.com/magiconair/properties (download)
github.com/mitchellh/mapstructure (download)
github.com/spf13/afero (download)
get "golang.org/x/text/transform": found meta tag get.metaImport{Prefix:"golang.org/x/text", VCS:"git", RepoRoot:"https://go.googlesource.com/text"} at //golang.org/x/text/transform?go-get=1
get "golang.org/x/text/transform": verifying non-authoritative meta tag
golang.org/x/text (download)
get "golang.org/x/text/unicode/norm": found meta tag get.metaImport{Prefix:"golang.org/x/text", VCS:"git", RepoRoot:"https://go.googlesource.com/text"} at //golang.org/x/text/unicode/norm?go-get=1
get "golang.org/x/text/unicode/norm": verifying non-authoritative meta tag
github.com/spf13/cast (download)
github.com/spf13/jwalterweatherman (download)
github.com/hashicorp/hcl (download)
github.com/agext/levenshtein (download)
github.com/apparentlymart/go-textseg (download)
github.com/mitchellh/go-wordwrap (download)
github.com/zclconf/go-cty (download)
cannot find package "github.com/hashicorp/hcl/hcl/printer" in any of:
	/usr/lib/go-1.15/src/github.com/hashicorp/hcl/hcl/printer (from $GOROOT)
	/home/astraluma/go/src/github.com/hashicorp/hcl/hcl/printer (from $GOPATH)
github.com/pelletier/go-toml (download)
github.com/subosito/gotenv (download)
get "gopkg.in/ini.v1": found meta tag get.metaImport{Prefix:"gopkg.in/ini.v1", VCS:"git", RepoRoot:"https://gopkg.in/ini.v1"} at //gopkg.in/ini.v1?go-get=1
gopkg.in/ini.v1 (download)
```

**Comment by dbaumgarten** [comment] 2021-08-15 11:35
This is strange.
I tried "go get -v github.com/dbaumgarten/yodk" myself and ran into another error. I fixed this error now (for the develop-branch for now) and now go get is working fine for me.

I could not reproduce your specific issue. And interestingly my output for go get looks slightly different.

What version of go are you using?

**Comment by AstraLuma** [comment] 2021-08-16 17:40
1.15.9 (which I think is whatever's in debian testing)

**Comment by dbaumgarten** [comment] 2021-08-16 18:46
Anything >=1.14 should be fine.
"go get -v github.com/dbaumgarten/yodk" is working fine for me, and the CI pipelines also has no issues.
Maybe you have a somehow corrupted mod-cache?
Try running "go clean -cache -modcache" and then "go get -v github.com/dbaumgarten/yodk".

If that doesn't work I have no idea whats wrong...

**Comment by dbaumgarten** [comment] 2021-08-21 12:56
Closed as can't reproduce. If you find a way to reliably reproduce this (for example inside a docker-container), please reopen this,

**Closed by dbaumgarten** 2021-08-21 12:56 UTC
Labels: bug
